/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import com.googlecode.javacpp.Loader;
import com.googlecode.javacv.Blobs;
import com.googlecode.javacv.cpp.opencv_core.IplImage;
import static com.googlecode.javacv.cpp.opencv_highgui.*;
import static com.googlecode.javacv.cpp.opencv_core.*;
import static com.googlecode.javacv.cpp.opencv_imgproc.*;
import static javaapplication3.BlobDemo.Highlight;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSlider;
import java.util.*;

/**
 *
 * @author leonardo
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    //CanvasFrame path = new CanvasFrame("Draw");
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton2.setText("Webcam");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JAVA CV - BLOB AND OBJECT DETECTION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Thread t;

        t = new Thread() {

            //JPanel jp = new JPanel();
            int oldx = 0, oldy = 0;

            private void paint(IplImage img, int posX, int posY) {
//        Graphics g = jp.getGraphics();
//        path.setSize(img.width(), img.height());
//        // g.clearRect(0, 0, img.width(), img.height());
//        g.setColor(Color.RED);
//        // g.fillOval(posX, posY, 20, 20);
//        g.drawLine(oldx, oldy, posY, posY);
//        oldx=posX;
//        oldy=posY;

                //System.out.println(posX + " , " + posY);
            }

            @Override
            public void run() {

                //Set The Panel Properties 
                JPanel controler = new JPanel();

                //Slider Colour 1
                int minVal = 0;
                int maxVal = 5;
                int minArea = 400;
                int maxArea = 100000;
                
                JLabel label = new JLabel();
                label.setText("Cor do Plano:" + minVal + "-" + maxVal);
                label.setSize(controler.getWidth(),30);
                controler.add(label);
                JSlider sliderMin = new JSlider(0, 255);
                JSlider sliderMax = new JSlider(0, 255);
                JSlider sliderAreaMin = new JSlider(0, 20000);
                JSlider sliderAreaMax = new JSlider(0, 20000);
                sliderAreaMax.setSize(controler.getWidth(),30);
                sliderAreaMin.setSize(controler.getWidth(),30);
                sliderMax.setSize(controler.getWidth(),30);
                sliderMin.setSize(controler.getWidth(),30);
                
                
                controler.add(sliderMin);
                controler.add(sliderMax);
                JLabel labelArea = new JLabel("MIN-MAX AREA");
                controler.add(labelArea);
                controler.add(sliderAreaMin);
                controler.add(sliderAreaMax);
                controler.add(new JLabel("______________"));

                //Slider Colour 2
                int minValCoulour2 = 0;
                int maxValCoulour2 = 0;
                JLabel labelColour2 = new JLabel();
                labelColour2.setText("Cor do bloco:" + minValCoulour2 + "-" + maxValCoulour2);
                labelColour2.setSize(controler.getWidth(),30);
                controler.add(labelColour2);
                JSlider sliderMinColour2 = new JSlider(0, 255);
                JSlider sliderMaxColour2 = new JSlider(0, 255);
                sliderMaxColour2.setSize(controler.getWidth(),30);
                sliderMinColour2.setSize(controler.getWidth(),30);
                controler.add(sliderMinColour2);
                controler.add(sliderMaxColour2);

                //Time For Blobs
                JLabel tempoLabel = new JLabel();
                tempoLabel.setSize(controler.getWidth(),30);
                controler.add(tempoLabel);
                
                //Frame
                JFrame frame = new JFrame();
                frame.add(controler);
                frame.setSize(250, 250);
                frame.setVisible(true);

                //Set camera device
                CvCapture camera = cvCreateCameraCapture(1);

                //Define Used Images 
                IplImage image;
                IplImage imgSatured = cvCreateImage(cvSize(640, 480), IPL_DEPTH_8U, 3);

                //Define Sequences
                CvSeq contour1 = new CvSeq(), contour2;
                CvSeq contour3 = new CvSeq();

                //Define Memory Manager
                CvMemStorage storage = CvMemStorage.create();

                //Max Area to Blob
                double areaM = 1000, areaC = 0;

                //Define Used Binary Images
                IplImage bin = cvCreateImage(cvSize(640, 480), IPL_DEPTH_8U, 1);
                IplImage bin_copy = cvCreateImage(cvSize(640, 480), IPL_DEPTH_8U, 1);

                IplImage bin2 = cvCreateImage(cvSize(640, 480), IPL_DEPTH_8U, 1);
                IplImage bin2_copy = cvCreateImage(cvSize(640, 480), IPL_DEPTH_8U, 1);

                //Colour 1
                CvScalar min;
                CvScalar max;

                //Colour 2
                CvScalar min2;
                CvScalar max2;

                //Loop for each Frame
                for (;;) {
                    //Get Values From Slider
                    minVal = sliderMin.getValue();
                    maxVal = sliderMax.getValue();
                    minValCoulour2 = sliderMinColour2.getValue();
                    maxValCoulour2 = sliderMaxColour2.getValue();
                    labelColour2.setText("Cor do bloco:" + minValCoulour2 + "-" + maxValCoulour2);
                    label.setText("Cor do Plano:" + minVal + "-" + maxVal);
                    minArea = sliderAreaMin.getValue();
                    maxArea = sliderAreaMax.getValue();
                    labelArea.setText("MIN-MAX AREA: "+ minArea+" : "+maxArea);
                    
                    

                    //Generic Colour 1
                    min = VisionControl.getMinColourHSV(minVal);
                    max = VisionControl.getMaxColourHSV(maxVal);

                    //Generic Colour 2
                    min2 = VisionControl.getMinColourHSV(minValCoulour2);
                    max2 = VisionControl.getMaxColourHSV(maxValCoulour2);

                    //Get Image From camera
                    image = cvQueryFrame(camera);

                    if (image != null) {
                        
                        imgSatured = VisionControl.convertImageToHSV(image);
                        cvSmooth(imgSatured, imgSatured, CV_GAUSSIAN, 5);

                        contour1 = new CvSeq();
                        contour3 = new CvSeq();
                        areaM = 1000;

                        cvInRangeS(imgSatured, min, max, bin);
                        cvInRangeS(imgSatured, min2, max2, bin2);
                        
                        //Flip Images to fit the real aspect
                        cvFlip(image, image, 1);
                        cvFlip(imgSatured, imgSatured, 1);
                        cvFlip(bin, bin, 1);
                        cvFlip(bin2, bin2, 1);
                        
                        //Eroding and Dilating Image To treat Noise
                        int ERODE_DILATE = 5;
                        cvErode(bin, bin, null, ERODE_DILATE);
                        //cvDilate(bin, bin, null, ERODE_DILATE);
                        cvErode(bin2, bin2, null, ERODE_DILATE);
                        //cvDilate(bin2, bin2, null, ERODE_DILATE);

                        bin_copy = bin;
                        bin2_copy = bin2;


                        long startTime = System.currentTimeMillis();    
                        
                            //Blob that identify Colour 1
                            List<BlobImage> listBlob1 = VisionControl.getBlob(bin_copy, imgSatured,minArea,maxArea);
                            //List<BlobImage> listBlob2 = VisionControl.getBlob(bin2_copy, imgSatured);
                            
                            System.out.println("List1: "+ listBlob1.size());
                            //System.out.println("List2: "+ listBlob2.size());
                            
                            
                            for (BlobImage bi : listBlob1){
                                VisionControl.HighlightElement(imgSatured,bi);
                                VisionControl.setXYLabel(imgSatured, bi.getCentro());
                            }
                            
                            VisionControl.drawlineFromList(imgSatured, VisionControl.getArrayOfCentros(listBlob1));
                            VisionControl.drawAngle(imgSatured, VisionControl.getArrayOfCentros(listBlob1));  //Rolou Nao
                         
                        long stopTime = System.currentTimeMillis();
                        
                        tempoLabel.setText("Tempo Blobs :"+(stopTime - startTime));

                        cvShowImage("Imagem Saturada", imgSatured);
                        cvShowImage("Colour 1", bin_copy);
                        cvShowImage("Colour 2", bin2_copy);
                        cvShowImage("Imagem Natural", image);

                        char c = (char) cvWaitKey(30);
                        if (c == 27) {
                            break;
                        }
                    }
                }
                cvReleaseCapture(camera);
            }
        };
        t.start();

    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}


//-----------  STASHED CODE - WAITING TO BE USED OR NOT -----------
//if (bin != null) {
//    cvFindContours(bin, storage, contour1, Loader.sizeof(CvContour.class), CV_RETR_LIST, CV_LINK_RUNS, cvPoint(0, 0));//CV_LINK_RUNS
//}
//contour2 = contour1;
//
//if (bin2 != null) {
//    cvFindContours(bin2, storage, contour3, Loader.sizeof(CvContour.class), CV_RETR_LIST, CV_LINK_RUNS, cvPoint(0, 0));
//}
//
//  while(contour1!=null && !contour1.isNull())
//  {
//  areaC = cvContourArea(contour1, CV_WHOLE_SEQ, 1);
//  if(areaC>areaM )
//      areaM = areaC;
//  contour1 = contour1.h_next();
//  }
//
//  while(contour2!=null && !contour2.isNull())
//  {
//      areaC = cvContourArea(contour2, CV_WHOLE_SEQ, 1);
//
//  if(areaC<areaM)
//  {
//      cvDrawContours(bin, contour2, CV_RGB(0, 0, 0), CV_RGB(0, 0, 0), 0, CV_FILLED, 8,cvPoint(0, 0));
//      System.out.println(areaC+"");
//  }
//  contour2 = contour2.h_next();
//  }
//  while(contour1!=null && !contour1.isNull())
//  {
//  CvSeq points = cvApproxPoly(contour1, Loader.sizeof(CvContour.class),storage, CV_POLY_APPROX_DP,3 , 0);//cvContourPerimeter(contour1)*0.02
//  areaC = cvContourArea(contour2, CV_WHOLE_SEQ, 1);
//
//  if(points.total() > 3 && points.total() < 6 )
//  {
//
//  }
//  contour1 = contour1.h_next();
//  }
//cvDrawContours(       bin, contour2, CV_RGB(255, 0,   0), CV_RGB(0, 0, 0), 0, 2, 8,cvPoint(0, 0));
//                        while (contour3 != null && !contour3.isNull()) {
//
//                            double area = cvContourArea(contour3, CV_WHOLE_SEQ, 0); //slice CV_WHOLE_SEQ is the Whole all the slices
//                            if (area < 3000) {
//                                cvDrawContours(imgSatured, contour3, CV_RGB(0, 0, 255), CV_RGB(0, 0, 0), 0, 2, 8, cvPoint(0, 0));
//                                //System.out.println("Area Blue: "+area);
//                            }
//                            contour3 = contour3.h_next();
//                        }
//
//                        while (contour1 != null && !contour1.isNull()) {
//
//                            double area = cvContourArea(contour1, CV_WHOLE_SEQ, 0); //slice CV_WHOLE_SEQ is the Whole all the slices
//                            if (area < 5000) {
//                                cvDrawContours(imgSatured, contour1, CV_RGB(255, 255, 0), CV_RGB(0, 0, 0), 0, 2, 8, cvPoint(0, 0));
//                            }
//                            // if(area<20000)
//                            //  System.out.println("Area Yellow "+count+": "+area);
//
//                            contour1 = contour1.h_next();
//                            // count ++;
//                        }
//
//                    int posX=0,posY=0;
//                    CvMoments moments = new CvMoments();
//                    cvMoments(bin, moments, 1);
//                    double mom10 = cvGetSpatialMoment(moments, 1, 0);
//                    double mom01 = cvGetSpatialMoment(moments, 0, 1);
//                    double area = cvGetCentralMoment(moments, 0, 0);
//                    posX = (int) (mom10 / area);
//                    posY = (int) (mom01 / area);
//                    // only if its a valid position
//                    if (posX > 0 && posY > 0) {
//                        paint(bin, posX, posY);
//                    }
//cvShowImage("Video", image);
//cvShowImage("Video2", imgGray);
//